
background {
    path = /home/lavander/Documents/Wallpapers/wallhaven-7j9p5y.jpg
    blur_passes = 1
}


source = ~/.cache/wal/colors-hyprland.conf

label {
    text = cmd[update:1000] echo "Sun Jan 11 10:56:59 PM EST 2026"
    color =  
    font_size = 25
    font_family = Noto Sans

    position = 0, 80
    halign = center
    valign = center
}

shape {
    size = 900, 60
    color = 
    rounding = -1 # circle
    border_size = 4
    border_color = 

    position = 0, 80
    halign = center
    valign = center
}
input-field {
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(255, 255, 255, 0) # no fill

    outer_color =   45deg
    check_color=   120deg
    fail_color=   40deg

    font_color = 
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}
